FROM openjdk:17
VOLUME /tmp

RUN mkdir /app
WORKDIR /app

ARG JAR_FILE=app.jar
COPY ./target/*.jar /app/app.jar

ARG PROFILE
ENV PROFILE=$PROFILE

ADD entrypoint.sh entrypoint.sh
RUN chmod 755 entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["./entrypoint.sh"]
