services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
      - '28017:28017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: