name: Build and Deploy JAR

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main"]

env:
  GH_KEY: ${{ secrets.GH_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure Maven Settings
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[{"id": "central", "url": "https://repo1.maven.org/maven2" }, {"id": "github", "url": "https://maven.pkg.github.com/frank000/cbio-jrasa", "snapshots":{"enabled":true } }]'
          active_profiles: >
            [
              "github"
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "frank000",
                "password": "${env.GH_KEY}"
              },
              {
                  "id": "github-repo",
                  "configuration": {
                    "httpHeaders": {
                      "property": {
                        "name": "Authorization",
                        "value": "${env.GH_KEY_AUTH}"
                      }
                    }
                  }
                }
            ]

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/your/project
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build JAR and Deploy to Remote Server
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          GH_KEY_AUTH: ${{ secrets.GH_KEY_AUTH }}
          IA_KEY: ${{ secrets.IA_KEY }}
          MINIO_PASSWORD: ${{ secrets.MINIO_PASSWORD }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          # Build JAR
          mvn clean package -DskipTests
          
          # Create SSH config to avoid host checking
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          
          # Copy JAR to remote server
          sshpass -p "$SERVER_PASSWORD" scp target/bot-0.0.1-SNAPSHOT.jar root@84.247.179.83:/root/applications/cbio/backend/
          
          # Restart application on remote server
          sshpass -p "$SERVER_PASSWORD" ssh root@84.247.179.83 '
            cd /root/applications/cbio/backend
            pkill -f "bot-0.0.1-SNAPSHOT.jar" || true
            nohup java -Xms512m -Xmx2g -Dspring.profiles.active=prd -jar bot-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
            echo "Application restarted"
          '